module.exports = {
  AU: [
    { id: "ACT", name: "Australian Capital Territory" },
    { id: "NSW", name: "New South Wales" },
    { id: "NT",  name: "Northern Territory" },
    { id: "QLD", name: "Queensland" },
    { id: "SA",  name: "South Australia" },
    { id: "TAS", name: "Tasmania" },
    { id: "VIC", name: "Victoria" },
    { id: "WA",  name: "Western Australia" }
  ],
  PH: [
    { id: "ABR", name: "Abra", CountryCode: "PH" },
    { id: "AGN", name: "Agusan del Norte", CountryCode: "PH" },
    { id: "AGS", name: "Agusan del Sur", CountryCode: "PH" },
    { id: "AKL", name: "Aklan", CountryCode: "PH" },
    { id: "ALB", name: "Albay", CountryCode: "PH" },
    { id: "ANT", name: "Antique", CountryCode: "PH" },
    { id: "APA", name: "Apayao", CountryCode: "PH" },
    { id: "AUR", name: "Aurora", CountryCode: "PH" },
    { id: "BAN", name: "Bataan", CountryCode: "PH" },
    { id: "BAS", name: "Basilan", CountryCode: "PH" },
    { id: "BEN", name: "Benguet", CountryCode: "PH" },
    { id: "BIL", name: "Biliran", CountryCode: "PH" },
    { id: "BOH", name: "Bohol", CountryCode: "PH" },
    { id: "BTG", name: "Batangas", CountryCode: "PH" },
    { id: "BTN", name: "Batanes", CountryCode: "PH" },
    { id: "BUK", name: "Bukidnon", CountryCode: "PH" },
    { id: "BUL", name: "Bulacan", CountryCode: "PH" },
    { id: "CAG", name: "Cagayan", CountryCode: "PH" },
    { id: "CAM", name: "Camiguin", CountryCode: "PH" },
    { id: "CAN", name: "Camarines Norte", CountryCode: "PH" },
    { id: "CAP", name: "Capiz", CountryCode: "PH" },
    { id: "CAS", name: "Camarines Sur", CountryCode: "PH" },
    { id: "CAT", name: "Catanduanes", CountryCode: "PH" },
    { id: "CAV", name: "Cavite", CountryCode: "PH" },
    { id: "CEB", name: "Cebu", CountryCode: "PH" },
    { id: "COM", name: "Compostela Valley", CountryCode: "PH" },
    { id: "DAO", name: "Davao Oriental", CountryCode: "PH" },
    { id: "DAS", name: "Davao del Sur", CountryCode: "PH" },
    { id: "DAV", name: "Davao del Norte", CountryCode: "PH" },
    { id: "EAS", name: "Eastern Samar", CountryCode: "PH" },
    { id: "GUI", name: "Guimaras", CountryCode: "PH" },
    { id: "IFU", name: "Ifugao", CountryCode: "PH" },
    { id: "ILI", name: "Iloilo", CountryCode: "PH" },
    { id: "ILN", name: "Ilocos Norte", CountryCode: "PH" },
    { id: "ILS", name: "Ilocos Sur", CountryCode: "PH" },
    { id: "ISA", name: "Isabela", CountryCode: "PH" },
    { id: "KAL", name: "Kalinga", CountryCode: "PH" },
    { id: "LAG", name: "Laguna", CountryCode: "PH" },
    { id: "LAN", name: "Lanao del Norte", CountryCode: "PH" },
    { id: "LAS", name: "Lanao del Sur", CountryCode: "PH" },
    { id: "LEY", name: "Leyte", CountryCode: "PH" },
    { id: "LUN", name: "La Union", CountryCode: "PH" },
    { id: "MAD", name: "Marinduque", CountryCode: "PH" },
    { id: "MAG", name: "Maguindanao", CountryCode: "PH" },
    { id: "MAS", name: "Masbate", CountryCode: "PH" },
    { id: "MDC", name: "Mindoro Occidental", CountryCode: "PH" },
    { id: "MDR", name: "Mindoro Oriental", CountryCode: "PH" },
    { id: "MOU", name: "Mountain Province", CountryCode: "PH" },
    { id: "MSC", name: "Misamis Occidental", CountryCode: "PH" },
    { id: "MSR", name: "Misamis Oriental", CountryCode: "PH" },
    { id: "NCO", name: "North Cotabato", CountryCode: "PH" },
    { id: "NEC", name: "Negros Occidental", CountryCode: "PH" },
    { id: "NER", name: "Negros Oriental", CountryCode: "PH" },
    { id: "NSA", name: "Northern Samar", CountryCode: "PH" },
    { id: "NUE", name: "Nueva Ecija", CountryCode: "PH" },
    { id: "NUV", name: "Nueva Vizcaya", CountryCode: "PH" },
    { id: "PAM", name: "Pampanga", CountryCode: "PH" },
    { id: "PAN", name: "Pangasinan", CountryCode: "PH" },
    { id: "PH", name: "Philippines", CountryCode: "PH" },
    { id: "PLW", name: "Palawan", CountryCode: "PH" },
    { id: "QUE", name: "Quezon", CountryCode: "PH" },
    { id: "QUI", name: "Quirino", CountryCode: "PH" },
    { id: "RIZ", name: "Rizal", CountryCode: "PH" },
    { id: "ROM", name: "Romblon", CountryCode: "PH" },
    { id: "SAR", name: "Sarangani", CountryCode: "PH" },
    { id: "SCO", name: "South Cotabato", CountryCode: "PH" },
    { id: "SIG", name: "Siquijor", CountryCode: "PH" },
    { id: "SLE", name: "Southern Leyte", CountryCode: "PH" },
    { id: "SLU", name: "Sulu", CountryCode: "PH" },
    { id: "SOR", name: "Sorsogon", CountryCode: "PH" },
    { id: "SUK", name: "Sultan Kudarat", CountryCode: "PH" },
    { id: "SUN", name: "Surigao del Norte", CountryCode: "PH" },
    { id: "SUR", name: "Surigao del Sur", CountryCode: "PH" },
    { id: "TAR", name: "Tarlac", CountryCode: "PH" },
    { id: "TAW", name: "Tawi-Tawi", CountryCode: "PH" },
    { id: "WSA", name: "Western Samar", CountryCode: "PH" },
    { id: "ZAN", name: "Zamboanga del Norte", CountryCode: "PH" },
    { id: "ZAS", name: "Zamboanga del Sur", CountryCode: "PH" },
    { id: "ZMB", name: "Zambales", CountryCode: "PH" },
    { id: "ZSI", name: "Zamboanga Sibuguey [Zamboanga Sibugay]", CountryCode: "PH" }
  ]
};