module.exports = [
  {countryAbbr: "AT", name: "Austria", currencyCode: "EUR"},
  {countryAbbr: "AU", name: "Australia", currencyCode: "AUD"},
  {countryAbbr: "BE", name: "Belgium", currencyCode: "EUR"},
  {countryAbbr: "BR", name: "Brazil", currencyCode: "BRL"},
  {countryAbbr: "CN", name: "China", currencyCode: "CNY"},
  {countryAbbr: "CY", name: "Cyprus", currencyCode: "EUR"},
  {countryAbbr: "EE", name: "Estonia", currencyCode: "EUR"},
  {countryAbbr: "FI", name: "Finland", currencyCode: "EUR"},
  {countryAbbr: "FR", name: "France", currencyCode: "EUR"},
  {countryAbbr: "DE", name: "Germany", currencyCode: "EUR"},
  {countryAbbr: "GR", name: "Greece", currencyCode: "EUR"},
  {countryAbbr: "IN", name: "India", currencyCode: "INR"},
  {countryAbbr: "IE", name: "Ireland", currencyCode: "EUR"},
  {countryAbbr: "IT", name: "Italy", currencyCode: "EUR"},
  {countryAbbr: "LV", name: "Latvia", currencyCode: "EUR"},
  {countryAbbr: "LT", name: "Lithuania", currencyCode: "EUR"},
  {countryAbbr: "LU", name: "Luxembourg", currencyCode: "EUR"},
  {countryAbbr: "MT", name: "Malta", currencyCode: "EUR"},
  {countryAbbr: "NL", name: "Netherlands", currencyCode: "EUR"},
  {countryAbbr: "PH", name: "Philippines (Republic of the Philippines)", currencyCode: "PHP"},
  {countryAbbr: "PT", name: "Portugal", currencyCode: "EUR"},
  {countryAbbr: "SK", name: "Slovakia", currencyCode: "EUR"},
  {countryAbbr: "SI", name: "Slovenia", currencyCode: "EUR"},
  {countryAbbr: "ES", name: "Spain", currencyCode: "EUR"},
  {countryAbbr: "MX", name: "Mexico", currencyCode: "MXN"},
  {countryAbbr: "GB", name: "United Kingdom", currencyCode: "GBP"},
  {countryAbbr: "US", name: "United States", currencyCode: "USD"}
]